language: groovy
jdk:
- oraclejdk7
before_script:
- rm -rf target
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: ZWue+sgLeTRkmx93PVP+O7hU9JEgTI09OvcDPS/+mHZamyfmIz5w5eWApZ4iYLbJcOqVLFxRqiZFC77XMJJ5VZ90u0w/zyOl53hXrv9V1qGE938ptAjuXrF127f4SO5SzR24NohP00EI1M1tLRnW5yplgeED8XK174XHN+vMABg=
  - secure: fmEi2iOIlVJ6PyDIcb4Gh8SwbL4mv/iwqn1ZEUqDnmK/UDWD+avAIe6G9BPRTHDAYZRfY9tUNgbcg4Sx03P+K/reRwrEjHBiYHMw5BdTcdSmLCoqiOlrwAx+KgtnB8iMSbMYP28Yo3t+ST1EpJEOv/ujbljqVkzf8h3D60ffFxI=
  - secure: fidVfBZfEmUAkaYGnDQn3fWfXSbMOEj7HvZu8tXBw/sLzMe1bNVT5f4KwJM440pCkvMx4pMHZKLQSxqLkeMkbaK9jFQVLsPIBBafJD93hxsQ2Ntg2mvg0Ep4BeFpRWAJN67KKmrEBjMFVg3vvuwtQcHgiLR47ZHS5v3sbsUSzG0=
